// src/react/HapticTrigger.tsx
import type { ReactNode } from 'react'
import { triggerAndroidHaptic } from '..'

export default function HapticTrigger({ children }: { children: ReactNode }) {
  return (
    <label>
      <input
        type="checkbox"
        // @ts-expect-error ...
        switch
        onChange={triggerAndroidHaptic}
        style={{ display: 'none' }}
      />
      {children}
    </label>
  )
}

// src/svelte/HapticTrigger.svelte
<script lang='ts'>
  import type { Snippet } from 'svelte'
  import { triggerAndroidHaptic } from '..'

  const { children }: { children: Snippet } = $props()
</script>

<label>
  <input
    type='checkbox'
    // @ts-expect-error
    switch
    style='display: none;'
    onchange={triggerAndroidHaptic}
  />
  {@render children()}
</label>
